// <auto-generated />
using AssignmentFlow.Application.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentFlow.Application.Migrations
{
    [DbContext(typeof(AssignmentFlowDbContext))]
    [Migration("20250428170323_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentFlow.Application.Assessments.Assessment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Assessment");
                });

            modelBuilder.Entity("AssignmentFlow.Application.Gradings.Grading", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RubricId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Gradings");
                });

            modelBuilder.Entity("AssignmentFlow.Application.Gradings.Grading", b =>
                {
                    b.OwnsMany("AssignmentFlow.Application.Gradings.CriteriaFilesMappingApiContract", "CriteriaFilesMappings", b1 =>
                        {
                            b1.Property<string>("GradingId")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.HasKey("GradingId", "__synthesizedOrdinal");

                            b1.ToTable("Gradings");

                            b1.ToJson("CriteriaFilesMappings");

                            b1.WithOwner()
                                .HasForeignKey("GradingId");

                            b1.OwnsOne("AssignmentFlow.Application.Gradings.ContentSelectorApiContract", "ContentSelector", b2 =>
                                {
                                    b2.Property<string>("CriteriaFilesMappingApiContractGradingId")
                                        .HasColumnType("character varying(50)");

                                    b2.Property<int>("CriteriaFilesMappingApiContract__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Pattern")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Strategy")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CriteriaFilesMappingApiContractGradingId", "CriteriaFilesMappingApiContract__synthesizedOrdinal");

                                    b2.ToTable("Gradings");

                                    b2.ToJson("ContentSelector");

                                    b2.WithOwner()
                                        .HasForeignKey("CriteriaFilesMappingApiContractGradingId", "CriteriaFilesMappingApiContract__synthesizedOrdinal");
                                });

                            b1.OwnsOne("AssignmentFlow.Application.Gradings.CriterionIdentityApiContract", "CriterionIdentity", b2 =>
                                {
                                    b2.Property<string>("CriteriaFilesMappingApiContractGradingId")
                                        .HasColumnType("character varying(50)");

                                    b2.Property<int>("CriteriaFilesMappingApiContract__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("CriterionName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("RubricId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CriteriaFilesMappingApiContractGradingId", "CriteriaFilesMappingApiContract__synthesizedOrdinal");

                                    b2.ToTable("Gradings");

                                    b2.ToJson("CriterionIdentity");

                                    b2.WithOwner()
                                        .HasForeignKey("CriteriaFilesMappingApiContractGradingId", "CriteriaFilesMappingApiContract__synthesizedOrdinal");
                                });

                            b1.Navigation("ContentSelector")
                                .IsRequired();

                            b1.Navigation("CriterionIdentity")
                                .IsRequired();
                        });

                    b.Navigation("CriteriaFilesMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
