// <auto-generated />
using AssignmentFlow.Application.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentFlow.Application.Migrations
{
    [DbContext(typeof(AssignmentFlowDbContext))]
    [Migration("20250428182431_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentFlow.Application.Assessments.Assessment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Assessment");
                });

            modelBuilder.Entity("AssignmentFlow.Application.Gradings.Grading", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RubricId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Gradings");
                });

            modelBuilder.Entity("AssignmentFlow.Application.Gradings.Grading", b =>
                {
                    b.OwnsMany("AssignmentFlow.Application.Gradings.CriterionAttachmentsSelectorApiContract", "CriterionAttachmentsSelectors", b1 =>
                        {
                            b1.Property<string>("GradingId")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Criterion")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GradingId", "__synthesizedOrdinal");

                            b1.ToTable("Gradings");

                            b1.ToJson("CriterionAttachmentsSelectors");

                            b1.WithOwner()
                                .HasForeignKey("GradingId");

                            b1.OwnsOne("AssignmentFlow.Application.Gradings.ContentSelectorApiContract", "Selector", b2 =>
                                {
                                    b2.Property<string>("CriterionAttachmentsSelectorApiContractGradingId")
                                        .HasColumnType("character varying(50)");

                                    b2.Property<int>("CriterionAttachmentsSelectorApiContract__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Pattern")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Strategy")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CriterionAttachmentsSelectorApiContractGradingId", "CriterionAttachmentsSelectorApiContract__synthesizedOrdinal");

                                    b2.ToTable("Gradings");

                                    b2.ToJson("Selector");

                                    b2.WithOwner()
                                        .HasForeignKey("CriterionAttachmentsSelectorApiContractGradingId", "CriterionAttachmentsSelectorApiContract__synthesizedOrdinal");
                                });

                            b1.Navigation("Selector")
                                .IsRequired();
                        });

                    b.Navigation("CriterionAttachmentsSelectors");
                });
#pragma warning restore 612, 618
        }
    }
}
