packages:
  - apps/*
  - libs/*
  - examples/*

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@nx-dotnet/core'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - protobufjs
  - sharp
  - unrs-resolver
