using EventFlow.ValueObjects;
using Google.Protobuf;
using Newtonsoft.Json;
using System.Collections;

namespace AssignmentFlow.Application.Assessments;

/// <summary>
/// Represents a collection of score breakdown items and provides the total score.
/// </summary>
[JsonConverter(typeof(ScoreBreakdownsConverter))]
public sealed class ScoreBreakdowns : ValueObject, IEnumerable<ScoreBreakdownItem>, IDeepCloneable<ScoreBreakdowns>
{
    /// <summary>
    /// Represents an empty collection of score breakdowns.
    /// </summary>
    public static ScoreBreakdowns Empty => new([]);

    /// <summary>
    /// Gets the array of score breakdown items.
    /// </summary>
    private List<ScoreBreakdownItem> BreakdownItems { get; }

    /// <summary>
    /// Gets the total percentage score calculated from the breakdown items.
    /// </summary>
    public Percentage TotalRawScore => Percentage.New(BreakdownItems.Sum(x => x.RawScore));

    /// <summary>
    /// Initializes a new instance of the <see cref="ScoreBreakdowns"/> class with the specified breakdown items.
    /// </summary>
    /// <param name="scoreValue">The array of score breakdown items.</param>
    private ScoreBreakdowns(List<ScoreBreakdownItem> scoreValue) => BreakdownItems = scoreValue;

    /// <summary>
    /// Creates a new instance of <see cref="ScoreBreakdowns"/> with the specified breakdown items.
    /// </summary>
    /// <param name="scoreBreakdownItems">The list of score breakdown items.</param>
    /// <returns>A new <see cref="ScoreBreakdowns"/> instance.</returns>
    public static ScoreBreakdowns New(List<ScoreBreakdownItem> scoreBreakdownItems) => new(scoreBreakdownItems);
    
    /// <summary>
    /// Provides the components used for equality comparison.
    /// </summary>
    /// <returns>An enumerable list of equality components.</returns>
    protected override IEnumerable<object> GetEqualityComponents()
    {
        foreach (var item in BreakdownItems)
        {
            yield return item;
        }
    }
    
    // Plus operator: Combines two lists (summing scores with the same criteria/tags)
    public static ScoreBreakdowns operator +(ScoreBreakdowns a, ScoreBreakdowns b)
    {
        foreach (var item in b.BreakdownItems)
        {
            var existingItem = a.BreakdownItems.FirstOrDefault(x => x.CriterionName == item.CriterionName);
            if (existingItem == null)
            {
                a.BreakdownItems.Add(item);
            }
            else
            {
                existingItem.RawScore += item.RawScore;
            }
        }

        return a;
    }

    public static ScoreBreakdowns operator -(ScoreBreakdowns a, ScoreBreakdowns b)
    {
        foreach (var item in b.BreakdownItems)
        {
            var existingItem = a.BreakdownItems.FirstOrDefault(x => x.CriterionName == item.CriterionName);
            if (existingItem == null)
            {
                a.BreakdownItems.Add(item);
            }
            else
            {
                existingItem.RawScore -= item.RawScore;
            }
        }

        return a;
    }

    /// <summary>
    /// Since grades generated by the AI grader for each item are in scale 100, we need to apply the criterion weight
    /// defined by the rubric to normalize them to the calculable score for each criterion.
    /// </summary>
    public ScoreBreakdowns NormalizedScores(HashSet<Criterion> criteria)
    {
        var normalizedScores = new List<ScoreBreakdownItem>(BreakdownItems.Count);
        foreach (var item in BreakdownItems)
        {
            normalizedScores.Add(item.NormalizedScore(criteria));
        }

        return ScoreBreakdowns.New(normalizedScores);
    }

    public ScoreBreakdowns AddOrUpdate(ScoreBreakdownItem item)
    {
        var clone = this.Clone();
        var existingItem = clone.BreakdownItems.FirstOrDefault(x => x.CriterionName == item.CriterionName);
        if (existingItem == null)
        {
            clone.BreakdownItems.Add(item);
        }
        else
        {
            clone.BreakdownItems.Remove(existingItem);
            clone.BreakdownItems.Add(item);
        }

        return clone;
    }

    public bool IsCompleted => BreakdownItems.All(item => item.IsCompleted);
    public bool IsCompletedWithErrors => BreakdownItems.Any(
        item => item.Status == "Failed"
        || !string.IsNullOrWhiteSpace(item.FailureReason));

    public IEnumerator<ScoreBreakdownItem> GetEnumerator()
    {
        return BreakdownItems.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public ScoreBreakdowns Clone()
    {
        return ScoreBreakdowns.New([..BreakdownItems.Select(item => item.Clone())]);
    }
}

public sealed class ScoreBreakdownsConverter : JsonConverter<ScoreBreakdowns>
{
    public override ScoreBreakdowns? ReadJson(JsonReader reader, Type objectType, ScoreBreakdowns? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null)
            return null;

        var breakdownItems = serializer.Deserialize<List<ScoreBreakdownItem>>(reader);

        return ScoreBreakdowns.New(breakdownItems ?? []);
    }
    public override bool CanWrite => false;

    public override void WriteJson(JsonWriter writer, ScoreBreakdowns? value, JsonSerializer serializer) => throw new NotSupportedException();
}

public static class ScoreBreakdownsExtension
{
    public static List<ScoreBreakdownApiContract> ToApiContracts(this ScoreBreakdowns scoreBreakdowns)
    {
        return [.. scoreBreakdowns.Select(sb => sb.ToApiContract())];
    }

    public static ScoreBreakdownApiContract ToApiContract(this ScoreBreakdownItem scoreBreakdownItem)
    {
        return new ScoreBreakdownApiContract
        {
            CriterionName = scoreBreakdownItem.CriterionName,
            PerformanceTag = scoreBreakdownItem.PerformanceTag,
            RawScore = scoreBreakdownItem.RawScore,
            MetadataJson = scoreBreakdownItem.MetadataJson,
            Status = scoreBreakdownItem.Status,
            Grader = scoreBreakdownItem.Grader
        };
    }

    public static List<FeedbackItemApiContract> ToApiContracts(this List<Feedback> feedbacks)
    {
        return feedbacks.ConvertAll(fb => new FeedbackItemApiContract
        {
            Id = fb.Identity.Value,
            Criterion = fb.Criterion,
            Comment = fb.Comment,
            FileRef = fb.Highlight.Attachment,
            LocationDataJson = fb.Highlight.LocationDataJson,
            Tag = fb.Tag,
        });
    }
}
