/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthenticatedRubricsViewRouteImport } from './routes/_authenticated/rubrics/view'
import { Route as AuthenticatedRubricsCreateRouteImport } from './routes/_authenticated/rubrics/create'
import { Route as AuthenticatedRubricsIdRouteImport } from './routes/_authenticated/rubrics/$id'
import { Route as AuthenticatedGradingsViewRouteImport } from './routes/_authenticated/gradings/view'
import { Route as AuthenticatedGradingsCreateRouteImport } from './routes/_authenticated/gradings/create'
import { Route as AuthenticatedGradingsGradingIdIndexRouteImport } from './routes/_authenticated/gradings/$gradingId/index'
import { Route as AuthenticatedGradingsGradingIdResultRouteImport } from './routes/_authenticated/gradings/$gradingId/result'
import { Route as AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRouteImport } from './routes/_authenticated/gradings/$gradingId/assessments/$assessmentId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedRubricsViewRoute =
  AuthenticatedRubricsViewRouteImport.update({
    id: '/rubrics/view',
    path: '/rubrics/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRubricsCreateRoute =
  AuthenticatedRubricsCreateRouteImport.update({
    id: '/rubrics/create',
    path: '/rubrics/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRubricsIdRoute = AuthenticatedRubricsIdRouteImport.update({
  id: '/rubrics/$id',
  path: '/rubrics/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradingsViewRoute =
  AuthenticatedGradingsViewRouteImport.update({
    id: '/gradings/view',
    path: '/gradings/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradingsCreateRoute =
  AuthenticatedGradingsCreateRouteImport.update({
    id: '/gradings/create',
    path: '/gradings/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradingsGradingIdIndexRoute =
  AuthenticatedGradingsGradingIdIndexRouteImport.update({
    id: '/gradings/$gradingId/',
    path: '/gradings/$gradingId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradingsGradingIdResultRoute =
  AuthenticatedGradingsGradingIdResultRouteImport.update({
    id: '/gradings/$gradingId/result',
    path: '/gradings/$gradingId/result',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute =
  AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRouteImport.update({
    id: '/gradings/$gradingId/assessments/$assessmentId',
    path: '/gradings/$gradingId/assessments/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/test': typeof AuthenticatedTestRoute
  '/gradings/create': typeof AuthenticatedGradingsCreateRoute
  '/gradings/view': typeof AuthenticatedGradingsViewRoute
  '/rubrics/$id': typeof AuthenticatedRubricsIdRoute
  '/rubrics/create': typeof AuthenticatedRubricsCreateRoute
  '/rubrics/view': typeof AuthenticatedRubricsViewRoute
  '/gradings/$gradingId/result': typeof AuthenticatedGradingsGradingIdResultRoute
  '/gradings/$gradingId': typeof AuthenticatedGradingsGradingIdIndexRoute
  '/gradings/$gradingId/assessments/$assessmentId': typeof AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/test': typeof AuthenticatedTestRoute
  '/gradings/create': typeof AuthenticatedGradingsCreateRoute
  '/gradings/view': typeof AuthenticatedGradingsViewRoute
  '/rubrics/$id': typeof AuthenticatedRubricsIdRoute
  '/rubrics/create': typeof AuthenticatedRubricsCreateRoute
  '/rubrics/view': typeof AuthenticatedRubricsViewRoute
  '/gradings/$gradingId/result': typeof AuthenticatedGradingsGradingIdResultRoute
  '/gradings/$gradingId': typeof AuthenticatedGradingsGradingIdIndexRoute
  '/gradings/$gradingId/assessments/$assessmentId': typeof AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/_authenticated/gradings/create': typeof AuthenticatedGradingsCreateRoute
  '/_authenticated/gradings/view': typeof AuthenticatedGradingsViewRoute
  '/_authenticated/rubrics/$id': typeof AuthenticatedRubricsIdRoute
  '/_authenticated/rubrics/create': typeof AuthenticatedRubricsCreateRoute
  '/_authenticated/rubrics/view': typeof AuthenticatedRubricsViewRoute
  '/_authenticated/gradings/$gradingId/result': typeof AuthenticatedGradingsGradingIdResultRoute
  '/_authenticated/gradings/$gradingId/': typeof AuthenticatedGradingsGradingIdIndexRoute
  '/_authenticated/gradings/$gradingId/assessments/$assessmentId': typeof AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/analytics'
    | '/chat'
    | '/home'
    | '/profile'
    | '/test'
    | '/gradings/create'
    | '/gradings/view'
    | '/rubrics/$id'
    | '/rubrics/create'
    | '/rubrics/view'
    | '/gradings/$gradingId/result'
    | '/gradings/$gradingId'
    | '/gradings/$gradingId/assessments/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/analytics'
    | '/chat'
    | '/home'
    | '/profile'
    | '/test'
    | '/gradings/create'
    | '/gradings/view'
    | '/rubrics/$id'
    | '/rubrics/create'
    | '/rubrics/view'
    | '/gradings/$gradingId/result'
    | '/gradings/$gradingId'
    | '/gradings/$gradingId/assessments/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_authenticated/analytics'
    | '/_authenticated/chat'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/test'
    | '/_authenticated/gradings/create'
    | '/_authenticated/gradings/view'
    | '/_authenticated/rubrics/$id'
    | '/_authenticated/rubrics/create'
    | '/_authenticated/rubrics/view'
    | '/_authenticated/gradings/$gradingId/result'
    | '/_authenticated/gradings/$gradingId/'
    | '/_authenticated/gradings/$gradingId/assessments/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/rubrics/view': {
      id: '/_authenticated/rubrics/view'
      path: '/rubrics/view'
      fullPath: '/rubrics/view'
      preLoaderRoute: typeof AuthenticatedRubricsViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rubrics/create': {
      id: '/_authenticated/rubrics/create'
      path: '/rubrics/create'
      fullPath: '/rubrics/create'
      preLoaderRoute: typeof AuthenticatedRubricsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rubrics/$id': {
      id: '/_authenticated/rubrics/$id'
      path: '/rubrics/$id'
      fullPath: '/rubrics/$id'
      preLoaderRoute: typeof AuthenticatedRubricsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradings/view': {
      id: '/_authenticated/gradings/view'
      path: '/gradings/view'
      fullPath: '/gradings/view'
      preLoaderRoute: typeof AuthenticatedGradingsViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradings/create': {
      id: '/_authenticated/gradings/create'
      path: '/gradings/create'
      fullPath: '/gradings/create'
      preLoaderRoute: typeof AuthenticatedGradingsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradings/$gradingId/': {
      id: '/_authenticated/gradings/$gradingId/'
      path: '/gradings/$gradingId'
      fullPath: '/gradings/$gradingId'
      preLoaderRoute: typeof AuthenticatedGradingsGradingIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradings/$gradingId/result': {
      id: '/_authenticated/gradings/$gradingId/result'
      path: '/gradings/$gradingId/result'
      fullPath: '/gradings/$gradingId/result'
      preLoaderRoute: typeof AuthenticatedGradingsGradingIdResultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradings/$gradingId/assessments/$assessmentId': {
      id: '/_authenticated/gradings/$gradingId/assessments/$assessmentId'
      path: '/gradings/$gradingId/assessments/$assessmentId'
      fullPath: '/gradings/$gradingId/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedGradingsCreateRoute: typeof AuthenticatedGradingsCreateRoute
  AuthenticatedGradingsViewRoute: typeof AuthenticatedGradingsViewRoute
  AuthenticatedRubricsIdRoute: typeof AuthenticatedRubricsIdRoute
  AuthenticatedRubricsCreateRoute: typeof AuthenticatedRubricsCreateRoute
  AuthenticatedRubricsViewRoute: typeof AuthenticatedRubricsViewRoute
  AuthenticatedGradingsGradingIdResultRoute: typeof AuthenticatedGradingsGradingIdResultRoute
  AuthenticatedGradingsGradingIdIndexRoute: typeof AuthenticatedGradingsGradingIdIndexRoute
  AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute: typeof AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedGradingsCreateRoute: AuthenticatedGradingsCreateRoute,
  AuthenticatedGradingsViewRoute: AuthenticatedGradingsViewRoute,
  AuthenticatedRubricsIdRoute: AuthenticatedRubricsIdRoute,
  AuthenticatedRubricsCreateRoute: AuthenticatedRubricsCreateRoute,
  AuthenticatedRubricsViewRoute: AuthenticatedRubricsViewRoute,
  AuthenticatedGradingsGradingIdResultRoute:
    AuthenticatedGradingsGradingIdResultRoute,
  AuthenticatedGradingsGradingIdIndexRoute:
    AuthenticatedGradingsGradingIdIndexRoute,
  AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute:
    AuthenticatedGradingsGradingIdAssessmentsAssessmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
